parameters:
    google_analytics.measurement_protocol.class: Kairos\GoogleAnalyticsBundle\MeasurementProtocol
    google_analytics.class: Kairos\GoogleAnalyticsBundle\ClassicTracker
    google_analytics_serverside.account_id:

services:
    google_analytics:
        class: %google_analytics.class%
        arguments:    [ %google_analytics_serverside.account_id% , %google_analytics_serverside.domain% ]
    google_analytics.measurement_protocol:
          class: %google_analytics.measurement_protocol.class%
          arguments:    [ @container, %google_analytics_serverside.account_id% , %google_analytics_serverside.domain%, %google_analytics_serverside.ssl% ]