filter:
    excluded_paths: [vendor/*]

tools:
    php_pdepend: true
    php_code_coverage: true
    php_analyzer: true
    php_code_sniffer: true

before_commands:
    - "composer install --prefer-source"
